=== miguelraya/LLSGI-03/marcadores.dtd
<!ELEMENT paises (pais)*>
<!ELEMENT pais (nombre|superficie|poblacion|densidad)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT densidad (#PCDATA)>

=== miguelraya/LLSGI-03/paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises SYSTEM "marcadores.dtd">
<paises>
<pais>
  <nombre>Espana</nombre>
  <superficie>504.783</superficie>
  <poblacion>46.791.000</poblacion>
  <densidad>93</densidad>
</pais>
<pais>
  <nombre>Costa Rica</nombre>
  <superficie>51.100</superficie>
  <poblacion>5.030.000</poblacion>
  <densidad>98</densidad>
</pais>
<pais>
  <nombre>Italia</nombre>
  <superficie>301.308</superficie>
  <poblacion>60.443.000</poblacion>
  <densidad>201</densidad>
</pais>
<pais>
  <nombre>Reino Unido</nombre>
  <superficie>242.500</superficie>
  <poblacion>66.636.000</poblacion>
  <densidad>275</densidad>
</pais>
<pais>
  <nombre>Argentina</nombre>
  <superficie>2.780.400</superficie>
  <poblacion>44.715.000</poblacion>
  <densidad>16</densidad>
</pais>
<pais>
  <nombre>Chile</nombre>
  <superficie>756.096</superficie>
  <poblacion>18.977.000</poblacion>
  <densidad>25</densidad>
</pais>
<pais>
  <nombre>Venezuela</nombre>
  <superficie>916.445</superficie>
  <poblacion>32.023.000</poblacion>
  <densidad>35</densidad>
</pais>
<pais>
  <nombre>Mexico</nombre>
  <superficie>1.959.248</superficie>
  <poblacion>125.956.000</poblacion>
  <densidad>64</densidad>
</pais>
<pais>
  <nombre>Francia</nombre>
  <superficie>543.941</superficie>
  <poblacion>65.231.000</poblacion>
  <densidad>120</densidad>
</pais>
<pais>
  <nombre>Estados Unidos</nombre>
  <superficie>9.148.020</superficie>
  <poblacion>329.071.000</poblacion>
  <densidad>36</densidad>
</pais>
<pais>
  <nombre>Finlandia</nombre>
  <superficie>303.912</superficie>
  <poblacion>5.523.000</poblacion>
  <densidad>18</densidad>
</pais>
<pais>
  <nombre>Rusia</nombre>
  <superficie>17.075.400</superficie>
  <poblacion>147.043.000</poblacion>
  <densidad>9</densidad>
</pais>
<pais>
  <nombre>Guinea Ecuatorial</nombre>
  <superficie>28.051</superficie>
  <poblacion>1.348.000</poblacion>
  <densidad>48</densidad>
</pais>
<pais>
  <nombre>Alemania</nombre>
  <superficie>357.386</superficie>
  <poblacion>83.082.000</poblacion>
  <densidad>232</densidad>
</pais>
<pais>
  <nombre>Australia</nombre>
  <superficie>7.688.126</superficie>
  <poblacion>25.150.000</poblacion>
  <densidad>3</densidad>
</pais>
<pais>
  <nombre>Nicaragua</nombre>
  <superficie>121.342</superficie>
  <poblacion>6.494.000</poblacion>
  <densidad>54</densidad>
</pais>
<pais>
  <nombre>Sri Lanka</nombre>
  <superficie>65.610</superficie>
  <poblacion>21.789.000</poblacion>
  <densidad>332</densidad>
</pais>
<pais>
  <nombre>Maldivas</nombre>
  <superficie>298</superficie>
  <poblacion>386.000</poblacion>
  <densidad>1.295</densidad>
</pais>
<pais>
  <nombre>Republica Checa</nombre>
  <superficie>78.867</superficie>
  <poblacion>10.640.000</poblacion>
  <densidad>135</densidad>
</pais>
<pais>
  <nombre>Cuba</nombre>
  <superficie>109.884</superficie>
  <poblacion>11.212.000</poblacion>
  <densidad>102</densidad>
</pais>
<pais>
  <nombre>Panama</nombre>
  <superficie>74.177</superficie>
  <poblacion>4.189.000</poblacion>
  <densidad>56</densidad>
</pais>
</paises>
